name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Esegui codestyle
        run: bash scripts/codestyle.sh
      - name: Esegui compile
        run: bash scripts/compile.sh